AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 300

Style/ClassAndModuleChildren:
  Enabled: false